# Generated by Django 5.1.3 on 2024-11-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_post_dislikes_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
