# Generated by Django 5.1.3 on 2024-11-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_notification_user_has_seen_alter_notification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post_pictures'),
        ),
    ]
